### ISSUE TITLE
sites_at_edges( self )

### ISSUE THREAD

**Issue by connorourke** [bjmorgan/lattice_mc#1]
Looks like the order is the wrong way around in sites_at_edges in cluster.py:;

You have:
```
        x_max = [ s for s in self.sites if s.r[0] == min_x ]
        x_min = [ s for s in self.sites if s.r[0] == max_x ]
```
rather than:
```
   x_max = [ s for s in self.sites if s.r[0] == max_x ]
   x_min = [ s for s in self.sites if s.r[0]  == min_x ]
```

**Comment by bjmorgan** [comment]
Fixed in commit 2776e094529fb55d584aef7eb51ff878559d9b84.

Turns out the unit test for this method *also* swapped minimum and maximum values, so was passing.
